server:
  port: 80

spring:
  application:
    name: openfeign-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  # 采样值介于0 ~ 1之间，1表示全部采集
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka
    register-with-eureka: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.glw.system.service.PaymentFeignService: debug