host:
  localUri: http://localhost:8001

server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
#          uri: ${host.localUri}
          uri: lb://hystrix-payment-service
          predicates:
            - Path=/payment/get/**
            - After=2020-08-02T13:34:03.255+08:00[Asia/Shanghai]
            - Cookie=username,666
            - Header=X-Request-Id, \d+
        - id: payment_route2
#          uri: ${host.localUri}
          uri: lb://hystrix-payment-service
          predicates:
            - Path=/payment/feign/timeout/**

eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka