server:
  port: 8002

spring:
  profiles:
    active: dev
  application:
    name: payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  # 采样值介于0 ~ 1之间，1表示全部采集

eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka
  instance:
    instance-id: payment2
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.glw.system.entity