server:
  port: 8001

host:
  public: 0.0.0.0
  private: 192.168.1.158
  local: 127.0.0.1

spring:
  application:
    name: zk-order-service
  cloud:
    zookeeper:
      connect-string: ${host.private}:2181